language: python
python:
  - "3.6"
script: python3 setup.py test

after_success:
  - pip install -r requirements/doc.pip
  - python3 setup.py build_sphinx

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # set in repo settings
  keep-history: true
  local-dir: docs/build/html
  verbose: true
  on:
    branch: master
